using System;
using System.IO;
using CatGuard.Gameplay.Battlefield;
using CatGuard.Gameplay.Levels;
using CatGuard.Gameplay.Waves;
using UnityEditor;
using UnityEngine;

namespace CatGuard.EditorTools.MapAuthoring
{
    public sealed class MapAuthoringCreationResult
    {
        public MapAuthoringCreationResult(BattlefieldConfig battlefield, WaveConfig wave, LevelConfig level)
        {
            Battlefield = battlefield;
            Wave = wave;
            Level = level;
        }

        public BattlefieldConfig Battlefield { get; }
        public WaveConfig Wave { get; }
        public LevelConfig Level { get; }
    }

    public static class MapAuthoringAssetFactory
    {
        public static MapAuthoringCreationResult CreateOrUpdateStarterLevel(
            string outputFolder,
            string assetPrefix,
            string battlefieldId,
            string levelId,
            string displayName,
            LevelConfig contentTemplate)
        {
            if (contentTemplate == null
                || contentTemplate.AvailableTowers == null
                || contentTemplate.AvailableTowers.Length == 0
                || contentTemplate.WaveConfig == null
                || contentTemplate.WaveConfig.Groups.Length == 0
                || contentTemplate.WaveConfig.Groups[0]?.EnemyConfig == null)
            {
                throw new InvalidDataException("A valid content template with towers, a wave, and enemies is required.");
            }

            if (string.IsNullOrWhiteSpace(outputFolder)
                || !outputFolder.Replace('\\', '/').StartsWith("Assets/", StringComparison.Ordinal))
            {
                throw new ArgumentException("Map authoring output folder must be inside Assets/.", nameof(outputFolder));
            }

            Directory.CreateDirectory(outputFolder);
            var mapPath = $"{outputFolder}/{assetPrefix}Battlefield.asset".Replace('\\', '/');
            var wavePath = $"{outputFolder}/{assetPrefix}Wave.asset".Replace('\\', '/');
            var levelPath = $"{outputFolder}/{assetPrefix}Level.asset".Replace('\\', '/');
            var map = EnsureAsset<BattlefieldConfig>(mapPath);
            var wave = EnsureAsset<WaveConfig>(wavePath);
            var level = EnsureAsset<LevelConfig>(levelPath);

            var sharedSpawn = new Vector2(-5.4f, 0f);
            var sharedGoal = new Vector2(5.4f, 0f);
            var ridgePoints = new[]
            {
                sharedSpawn,
                new Vector2(-3.8f, 1.35f),
                new Vector2(-0.8f, 1.65f),
                new Vector2(2.4f, 1.35f),
                sharedGoal
            };
            var creekPoints = new[]
            {
                sharedSpawn,
                new Vector2(-3.7f, -1.35f),
                new Vector2(0.9f, -1.6f),
                new Vector2(3.7f, -1.25f),
                sharedGoal
            };

            map.Configure(
                battlefieldId,
                displayName,
                "garden_day",
                "authoring_sandbox",
                BattlefieldCameraMode.FixedOverview,
                new Rect(-6f, -3.6f, 12f, 7.2f),
                new Rect(-6f, -3.6f, 12f, 7.2f),
                Vector2.zero,
                7.2f,
                ridgePoints,
                0.46f,
                sharedSpawn,
                sharedGoal,
                1f,
                new[]
                {
                    new BattlefieldZone("center_pocket", new Rect(-3f, -0.55f, 6f, 1.1f)),
                    new BattlefieldZone("north_pocket", new Rect(-4.5f, 2.35f, 9f, 0.95f)),
                    new BattlefieldZone("south_pocket", new Rect(-4.5f, -3.3f, 9f, 0.95f))
                },
                new[]
                {
                    new BattlefieldZone("center_prop", new Rect(-0.42f, -0.42f, 0.84f, 0.84f))
                },
                new[]
                {
                    new BattlefieldDecorationAnchor("center_prop", Vector2.zero, 1f, false),
                    new BattlefieldDecorationAnchor("ridge_marker", new Vector2(0f, 2.65f), 0.7f, true)
                });
            map.ConfigureRoutes(new[]
            {
                new PathRouteConfig(
                    "ridge",
                    "Ridge Route",
                    ridgePoints,
                    sharedSpawn,
                    sharedGoal,
                    "north_ridge",
                    0.46f,
                    1f,
                    new[] { "ground", "fork" },
                    0f,
                    "Starter route generated by the E4 authoring pipeline."),
                new PathRouteConfig(
                    "creek",
                    "Creek Route",
                    creekPoints,
                    sharedSpawn,
                    sharedGoal,
                    "south_creek",
                    0.46f,
                    1f,
                    new[] { "ground", "fork" },
                    0f,
                    "Starter route generated by the E4 authoring pipeline.")
            });
            map.ConfigureDesignCard(
                "Authoring sandbox / medium",
                "Shared endpoints split into high and low routes around a protected center pocket.",
                new[] { "Long-range coverage across the fork", "Splash coverage near the shared goal" },
                "Simultaneous pressure from routes with different curvature.",
                "Map-scale control is strongest near the fork and shared goal.",
                "High-contrast route colors, distinct vertical lanes, and no mandatory precision placement.");

            var primaryEnemy = contentTemplate.WaveConfig.Groups[0].EnemyConfig;
            var secondaryEnemy = contentTemplate.WaveConfig.Groups.Length > 1
                ? contentTemplate.WaveConfig.Groups[1].EnemyConfig
                : primaryEnemy;
            wave.Configure(new[]
            {
                new WaveEnemyGroup(primaryEnemy, 4, 0.7f, 0f, 1f, 1f, "ridge"),
                new WaveEnemyGroup(secondaryEnemy, 4, 0.75f, 0f, 1f, 1f, "creek")
            });
            wave.ConfigureConcurrentGroups(true);

            level.Configure(
                levelId,
                displayName,
                8,
                4,
                3,
                1f,
                new Vector2(-1.5f, -2.7f),
                ridgePoints,
                contentTemplate.AvailableTowers,
                wave,
                0,
                0,
                Array.Empty<string>(),
                string.Empty,
                contentTemplate.StartingBattleFish);
            level.ConfigureBattlefield(map);

            EditorUtility.SetDirty(map);
            EditorUtility.SetDirty(wave);
            EditorUtility.SetDirty(level);
            AssetDatabase.SaveAssets();
            return new MapAuthoringCreationResult(map, wave, level);
        }

        private static T EnsureAsset<T>(string path)
            where T : ScriptableObject
        {
            var asset = AssetDatabase.LoadAssetAtPath<T>(path);
            if (asset != null)
            {
                return asset;
            }

            asset = ScriptableObject.CreateInstance<T>();
            asset.name = Path.GetFileNameWithoutExtension(path);
            AssetDatabase.CreateAsset(asset, path);
            return asset;
        }
    }
}
